import{a as p,S as m,i as d}from"./assets/vendor-CNqCr-V-.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(r){if(r.ep)return;r.ep=!0;const e=t(r);fetch(r.href,e)}})();const y="https://pixabay.com/api/",h="53387136-aec480b6b069bc63c101bbeda",g=40;async function w(o,s=1,t=g){const n=String(o||"").trim();if(!n)throw new Error("Empty search query");const r={key:h,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t};try{return(await p.get(y,{params:r})).data}catch(e){throw e.response?new Error(`API error: ${e.response.status} ${e.response.statusText}`):e.request?new Error("Network error: no response from server"):new Error(e.message)}}let i=null;function L(o){const s=o.map(({webformatURL:n,largeImageURL:r,tags:e,likes:a,views:l,comments:u,downloads:f})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${r}">
    <img class="gallery-image" src="${n}" alt="${e}" />
  </a>
  <div class="info">
    <p class="info-item">Likes: <span class="info-span">${a}</span></p>
    <p class="info-item">Views: <span class="info-span">${l}</span></p>
    <p class="info-item">Comments: <span class="info-span">${u}</span></p>
    <p class="info-item">Downloads: <span class="info-span">${f}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",s),i?i.refresh():i=new m(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function b(){document.querySelector(".gallery").innerHTML=""}function S(){document.querySelector(".loader").classList.remove("hidden")}function q(){document.querySelector(".loader").classList.add("hidden")}const E=document.querySelector(".form");document.querySelector(".gallery");E.addEventListener("submit",P);function c(o){d.error({title:"Помилка",message:o,position:"topRight",timeout:4e3})}async function P(o){o.preventDefault();const s=o.target.elements.searchQuery.value.trim();if(!s){c("Будь ласка, введіть пошуковий запит");return}b(),S();try{const t=await w(s);if(!t||!t.hits||t.hits.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}L(t.hits)}catch(t){c("Помилка: "+(t.message||t))}finally{q()}}
//# sourceMappingURL=index.js.map
