import{a as f,S as p}from"./assets/vendor-BprjmLGJ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const e of r)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(r){const e={};return r.integrity&&(e.integrity=r.integrity),r.referrerPolicy&&(e.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?e.credentials="include":r.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(r){if(r.ep)return;r.ep=!0;const e=t(r);fetch(r.href,e)}})();const d="https://pixabay.com/api/",m="53387136-aec480b6b069bc63c101bbeda",y=40;async function h(o,s=1,t=y){const n=String(o||"").trim();if(!n)throw new Error("Empty search query");const r={key:m,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t};try{return(await f.get(d,{params:r})).data}catch(e){throw e.response?new Error(`API error: ${e.response.status} ${e.response.statusText}`):e.request?new Error("Network error: no response from server"):new Error(e.message)}}let i=null;function g(o){const s=o.map(({webformatURL:n,largeImageURL:r,tags:e,likes:a,views:c,comments:l,downloads:u})=>`
<li class="gallery-item">
  <a class="gallery-link" href="${r}">
    <img class="gallery-image" src="${n}" alt="${e}" />
  </a>
  <div class="info">
    <p class="info-item">Likes: <span class="info-span">${a}</span></p>
    <p class="info-item">Views: <span class="info-span">${c}</span></p>
    <p class="info-item">Comments: <span class="info-span">${l}</span></p>
    <p class="info-item">Downloads: <span class="info-span">${u}</span></p>
  </div>
</li>`).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",s),i?i.refresh():i=new p(".gallery a",{captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function w(){document.querySelector(".gallery").innerHTML=""}function L(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}const E=document.querySelector(".form");document.querySelector(".gallery");E.addEventListener("submit",S);async function S(o){o.preventDefault();const s=o.target.elements.searchQuery.value.trim();if(!s){alert("Please enter a search term");return}w(),L();try{const t=await h(s);if(!t||!t.hits||t.hits.length===0){alert("No images found");return}g(t.hits)}catch(t){alert("Error: "+(t.message||t))}finally{b()}}
//# sourceMappingURL=index.js.map
